# docker-compose.yml
version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
     - POSTGRES_DB=my_db
     - POSTGRES_USER=root
     - POSTGRES_PASSWORD=123456
    ports:
      - '5430:5430'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
